### ISSUE TITLE
Import der Datensicherung schlägt mit Docker und der alpha 2 fehl

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1459]
Folgende Fehlermeldung erhält man:

Fatal error: Uncaught Error: Class 'Db' not found in /var/www/html/admin/backup.import.php:98 Stack trace: #0 /var/www/html/admin/index.php(338): require() #1 {main} thrown in /var/www/html/admin/backup.import.php on line 98

**Comment by danielrichter78** [comment]
Fatal error: Uncaught Error: Class 'phpMyFAQ\Db\Strings' not found in /var/www/html/src/phpMyFAQ/Db/Helper.php:138 Stack trace: #0 /var/www/html/src/phpMyFAQ/Db/Helper.php(112): phpMyFAQ\Db\Helper::alignTablePrefixByPattern('DELETE FROM faq...', 'DELETE FROM', '', '') #1 /var/www/html/admin/backup.import.php(100): phpMyFAQ\Db\Helper::alignTablePrefix('DELETE FROM faq...', '', '') #2 /var/www/html/admin/index.php(338): require('/var/www/html/a...') #3 {main} thrown in /var/www/html/src/phpMyFAQ/Db/Helper.php on line 138

**Comment by thorsten** [comment]
yep, fixed now.
