### ISSUE TITLE
Removing category does not work

### ISSUE THREAD

**Issue by RemBdev** [thorsten/phpMyFAQ#2835]
**Describe the bug**
When removing a category i get a fatal error and the category is not removed.

```
phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Category\CategoryImage::setFileName(): Argument #1 ($fileName) must be of type string, null given, called in /var/www/html/admin/category.main.php on line 283'

Stack trace:

#0 /var/www/html/admin/category.main.php(283): phpMyFAQ\Category\CategoryImage->setFileName(NULL)
#1 /var/www/html/admin/index.php(392): require('/var/www/html/a...')
#2 {main}
Thrown in '/var/www/html/src/phpMyFAQ/Category/CategoryImage.php' on line 85
```

**To Reproduce**
Remove a sub-category.

**Expected behavior**
Category should be removed without an error.

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/29834979/53acda1c-4252-4868-b207-372ec5295cb6)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.2.4
- PHP version 8.2
- Database mysql
- Elasticsearch no

**Comment by RemBdev** [comment]
Thank you, works now!
