### ISSUE TITLE
nightly 2024-07-04 / Activating Markdown Editor results in error when viewing FAQ

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3084]
After activating the Markdown Editor option,

![markdown-editor-2](https://github.com/thorsten/phpMyFAQ/assets/112912128/208d7127-ec5b-4924-8c0f-4b7c3bbc565d)

opening a FAQ post in frontend results in the following error:

```
phpMyFAQ Fatal error
Uncaught exception: 'ErrorException'

Message: 'mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead'

Stack trace:

#0 [internal function]: phpMyFAQ\Core\Error::errorHandler(8192, 'mb_convert_enco...', '/home/www/cc10....', 480)
#1 /home/www/cc10.de/src/libs/erusev/parsedown-extra/ParsedownExtra.php(480): mb_convert_encoding('
FAQ3 in DE-H...', 'HTML-ENTITIES', 'UTF-8')
#2 /home/www/cc10.de/src/libs/erusev/parsedown-extra/ParsedownExtra.php(232): ParsedownExtra->processTag('

FAQ3 in DE-H...')
#3 /home/www/cc10.de/src/libs/erusev/parsedown/Parsedown.php(276): ParsedownExtra->blockMarkupComplete(Array)
#4 /home/www/cc10.de/src/libs/erusev/parsedown/Parsedown.php(39): Parsedown->lines(Array)
#5 /home/www/cc10.de/src/libs/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text('

FAQ3 in DE-H...')
#6 /home/www/cc10.de/faq.php(116): ParsedownExtra->text('

FAQ3 in DE-H...')
#7 /home/www/cc10.de/index.php(778): require('/home/www/cc10....')
#8 {main}

Thrown in '/home/www/cc10.de/src/libs/erusev/parsedown-extra/ParsedownExtra.php' on line 480
```

Site: cc10.de / nightly 2024-07-04
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Caused by https://github.com/erusev/parsedown-extra/issues/177
