### ISSUE TITLE
phpMyFAQ 3.2.8 throws Message: 'Call to a member function format() on null'

### ISSUE THREAD

**Issue by prbt2016** [thorsten/phpMyFAQ#3113]
**Describe the bug**
Hello ,

I was in the process of manual installation of phpMyFAQ 3.2.8 on AlmaLinux release 8.10 (Cerulean Leopard) with  PHP 8.1.29 , 
MYSQL 8.0.38, Apache 2.4.54. However, when I try to add a FAQ, the following error is thrown i.e : 

Uncaught exception: 'Error'

Message: 'Call to a member function format() on null'

**To Reproduce**

1. Go to 'Content->Add New FAQ'
2. Enter Question and Answer
3. Click Save
4. See error : Message: 'Call to a member function format() on null'

**Expected behavior**
FAQ should be added

**Screenshots**
![testfaqpng](https://github.com/user-attachments/assets/2ea42d2b-198d-44b3-8333-59b2a80eefff)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.2.8
- PHP version - 8.1.29
- Database -  8.0.38
- Elasticsearch yes/no - No

**Desktop (please complete the following information):**

- OS: [e.g. iOS] - AlmaLinux release 8.10 (Cerulean Leopard)
- Browser [e.g. chrome, safari] - Firefox 
- Version [e.g. 22] - 115.13.0esr (64-bit)

**Additional context**

Full error with stack trace : 

Uncaught exception: 'Error'

Message: 'Call to a member function format() on null'

Stack trace:

#0 /{{PATH}}/{{TO}}/{{MYFAQ}}/admin/record.add.php(122): phpMyFAQ\Faq->create(Object(phpMyFAQ\Entity\FaqEntity))
#1 /{{PATH}}/{{TO}}/{{MYFAQ}}/admin/index.php(363): require('/home/soft/publ...')
#2 {main}

Thrown in '/{{PATH}}/{{TO}}/{{MYFAQ}}/src/phpMyFAQ/Faq.php' on line 930

Can you please replicate this error at your end?.

**Comment by prbt2016** [comment]
Hello, 

Thanks . Checked 3.2.9 . It's resolved. 

Regards.
