### ISSUE TITLE
Forgotten password failure

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#3126]
Fatal error: Uncaught Error: mysqli object is already closed in /mnt/web109/e2/67/54355767/htdocs/FQA_20240728/src/phpMyFAQ/Database/Mysqli.php:346 Stack trace: #0 /mnt/web109/e2/67/54355767/htdocs/FQA_20240728/src/phpMyFAQ/Database/Mysqli.php(346): mysqli->close() #1 [internal function]: phpMyFAQ\Database\Mysqli->__destruct() #2 {main} thrown in /mnt/web109/e2/67/54355767/htdocs/FQA_20240728/src/phpMyFAQ/Database/Mysqli.php on line 346

**Describe the bug**
Trying to reset the password failed. The header of the page is not correct and the user is always getting the error username and email address are incorrect

**To Reproduce**
Go to the website and select forgotten password

**Expected behavior**
Page with correct pageheader and a message that the link or new password is send to the mail address

**Screenshots**
 
![image](https://github.com/user-attachments/assets/54096dd0-a05d-4bec-a979-6ff73e4d706d)
![Screen Shot 07-28-24 at 05 30 PM](https://github.com/user-attachments/assets/f58ddc31-cf1a-43a1-9b8a-a1aa13548d5a)

**Debug data
Fatal error: Uncaught Error: mysqli object is already closed in /mnt/web109/e2/67/54355767/htdocs/FQA_20240728/src/phpMyFAQ/Database/Mysqli.php:346 Stack trace: #0 /mnt/web109/e2/67/54355767/htdocs/FQA_20240728/src/phpMyFAQ/Database/Mysqli.php(346): mysqli->close() #1 [internal function]: phpMyFAQ\Database\Mysqli->__destruct() #2 {main} thrown in /mnt/web109/e2/67/54355767/htdocs/FQA_20240728/src/phpMyFAQ/Database/Mysqli.php on line 346

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.2.9
- PHP version 8.1
- Database phpmysql
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windwos 11
- Browser [e.g. chrome, safari] Chrome / edge

**Comment by danielrichter78** [comment]
Bei mir klappt es ohne Probleme.

Die E-Mail sieht dann wie folgt aus:

Betreff:
[FAQNAME] Username / password request <- englischer Text

E-Mail-Text:
Vielen Dank für die Abfrage deiner Account Informationen. <- man fragt ja nicht ab und erhält sie nicht, man erhält ja ein neues PW, könnte man textlich ändern
Username: admin
New Password: 5tgRc7xX <- ist ein neues Kennwort

Bitte ein neues Passwort im Adminbereich der FAQ setzen. <- kommt diese Zeile auch, wenn man kein Admin ist und nur ein normaler Benutzer? Wäre dann nicht richtig.


phpMyFAQ:

phpMyFAQ version 3.2.9
PHP version 8.3.8
Database mySQL 8.0.35
Elasticsearch no

Desktop (please complete the following information):

OS: [e.g. iOS] macOS
Browser [e.g. chrome, safari] Safari
Version [e.g. 22] 17.6

**Comment by ton-helmerhorst** [comment]
Thank
